[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=reports/allure-results --clean-alluredir --reruns 2 --reruns-delay 1
markers =
    smoke: 冒烟测试
    regression: 回归测试
    database: 数据库测试
    api: 接口测试